[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysrc"
version = "0.1.0"
description = "Data manager for pre-/postprocessing"

[tool.setuptools.packages.find]
where = ["."]
include = ["pysrc*"]